#!/usr/bin/env python3
"""
首页 Hero 背景图优化：生成多尺寸 / 多格式响应式图片 + LQIP 占位图。

这是一个**可选的离线工具**，不参与站点构建。只有当 `hero-bg.jpg` 原图被替换时才需要重新运行。

用法：
    pip install "Pillow>=11.3"      # 需要 AVIF 支持，Pillow 11.3+ 内置
    python scripts/optimize-hero-bg.py

产物（写入 docs/public/images/hero/）：
    hero-{640,960,1280,1920,2560}.{avif,webp,jpg}
    ../hero-lqip.txt                # 极小占位图的 base64（内联进 CSS，零额外请求）

调参集中在 QUALITY / WIDTHS 两个常量里；改完重跑即可覆盖产物。
"""

from __future__ import annotations

import base64
import io
import sys
from pathlib import Path

from PIL import Image, ImageFilter

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "scripts" / "src" / "hero-bg.jpg"
OUT_DIR = ROOT / "docs" / "public" / "images" / "hero"
# 注意：这里只作为调试留档，不要放进 docs/public/ —— 会被一起部署上线
LQIP_OUT = ROOT / "scripts" / "hero-lqip.txt"
# LQIP JS 模块：被 Layout.vue 直接 import，构建时内联进 bundle（零运行时请求）
LQIP_JS_OUT = ROOT / "docs" / ".vitepress" / "theme" / "hero-lqip.js"

# 断点选择：sizes="100vw" 下，浏览器按 视口宽 × DPR 挑选最近的档位。
# 640 覆盖小屏手机，2560 覆盖 2x 的大屏桌面；原图宽 2560，故到此为止。
WIDTHS = (640, 960, 1280, 1920, 2560)

# 质量控制：以「投屏后看不出压缩痕迹」为准绳调出来的保守值。
# AVIF 用很低的质量数就能换取极小体积；WebP/JPEG 依次放宽。
QUALITY = {
    "avif": 46,
    "webp": 70,
    "jpg": 72,
}

LQIP_WIDTH = 24  # 占位图宽度，模糊放大后作为淡入前的底


def save_avif(img: Image.Image, path: Path) -> None:
    img.save(path, format="AVIF", quality=QUALITY["avif"], speed=2)


def save_webp(img: Image.Image, path: Path) -> None:
    img.save(path, format="WEBP", quality=QUALITY["webp"], method=6)


def save_jpg(img: Image.Image, path: Path) -> None:
    # progressive + optimize：基线 JPEG 之外的额外体积优化，解码时可先出粗图
    img.save(
        path,
        format="JPEG",
        quality=QUALITY["jpg"],
        optimize=True,
        progressive=True,
    )


SAVERS = {"avif": save_avif, "webp": save_webp, "jpg": save_jpg}


def build_lqip(img: Image.Image) -> str:
    """生成 24px 宽的模糊缩略图，输出 data URI 字符串。"""
    w = LQIP_WIDTH
    h = max(1, round(img.height * w / img.width))
    tiny = img.resize((w, h), Image.LANCZOS).filter(ImageFilter.GaussianBlur(0.6))
    buf = io.BytesIO()
    tiny.save(buf, format="JPEG", quality=40, optimize=True)
    data = buf.getvalue()
    return f"data:image/jpeg;base64,{base64.b64encode(data).decode('ascii')}"


def kb(n: int) -> str:
    return f"{n / 1024:.1f} KB"


def main() -> int:
    if not SRC.exists():
        print(f"[x] 找不到原图：{SRC}", file=sys.stderr)
        return 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)

    with Image.open(SRC) as src:
        src.load()
        img = src.convert("RGB")
        print(f"原图：{img.width}x{img.height}  {kb(SRC.stat().st_size)}\n")

        print(f"{'档位':>6}  {'AVIF':>10}  {'WebP':>10}  {'JPEG':>10}")
        print("-" * 44)
        for w in WIDTHS:
            if w > img.width:
                continue
            h = round(img.height * w / img.width)
            resized = img.resize((w, h), Image.LANCZOS)
            row = []
            for fmt, saver in SAVERS.items():
                path = OUT_DIR / f"hero-{w}.{fmt}"
                saver(resized, path)
                row.append(kb(path.stat().st_size))
            print(f"{w:>6}  {row[0]:>10}  {row[1]:>10}  {row[2]:>10}")

    lqip = build_lqip(img)
    LQIP_OUT.write_text(lqip, encoding="ascii")
    print(f"\nLQIP 占位图：{len(lqip)} 字节（内联，不产生额外请求） -> {LQIP_OUT.relative_to(ROOT)}")

    # 生成 JS 模块供 Layout.vue import（构建时 Vite 内联，不产生运行时请求）
    LQIP_JS_OUT.parent.mkdir(parents=True, exist_ok=True)
    LQIP_JS_OUT.write_text(
        f"// Auto-generated by scripts/optimize-hero-bg.py — do not edit manually\n"
        f"export const HERO_LQIP = {lqip!r}\n",
        encoding="utf-8",
    )
    print(f"LQIP JS 模块：{LQIP_JS_OUT.relative_to(ROOT)}")

    print(f"产物目录：{OUT_DIR.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
